version: '3'
services:
  api:
    build: ./api   
    environment:
      - PORT=3000
      - CACHE=redis
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=securing-api
    # Docker doesn't support dynamic ports for each replica out-of-the-box
    # ports:
    #   - "3000:3000"
    depends_on:
      cache:
        # use service_started instead of service_healthy to speed up the startup
        condition: service_started
      db:
        condition: service_started
    deploy:
      replicas: 2
    networks:
      - my_company_network
    # Comment volumes and command if prefer to use "production" system
    volumes:
      - ./api:/usr/src/app        # Mount local code to container
      - /usr/src/app/node_modules # Prevent node_modules from being overwritten
    command: npm run start        # Start with nodemon
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      start_period: 10s
      interval: 30s
      timeout: 2s
      retries: 10
  load_balancer:
    build: ./load_balancer
    ports:
      - "8080:8080"
    networks:
      - my_company_network
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      api:
        condition: service_started
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - my_company_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 2s
      retries: 10
  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=securing-api
    ports:
      - '5432:5432'
    networks:
      - my_company_network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 2s
      retries: 10
  cdn:
    build: ./cdn
    ports:
      - "80:80"
    networks:
      - my_company_network
    volumes:
      - ./cdn/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./cdn/static:/usr/local/openresty/nginx/html/static
    depends_on:
      load_balancer:
        condition: service_started
      s3:
        condition: service_started
  s3:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - "./s3/setup/init-s3.py:/etc/localstack/init/ready.d/init-s3.py"  # ready hook
      - "./s3/data:/tmp/data"
    networks:
      - my_company_network

networks:
  my_company_network:

volumes:
  cache:
    driver: local
  db-data: