version: '3'
services:
  api:
    build: ./api   
    environment:
      - PORT=3000
      - CACHE=redis
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      cache:
        # use service_started instead of service_healthy to speed up the startup
        condition: service_started
    deploy:
      replicas: 2
    networks:
      - my_company_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      start_period: 10s
      interval: 30s
      timeout: 2s
      retries: 10
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - my_company_network
    depends_on:
      api:
        condition: service_started
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - my_company_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 2s
      retries: 10

networks:
  my_company_network:

volumes:
  cache:
    driver: local