version: '3'
services:
  api:
    build: ./api   
    environment:
      - PORT=3000
      - CACHE=redis
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    # Docker doesn't support dynamic ports for each replica out-of-the-box
    # ports:
    #   - "3000:3000"
    depends_on:
      cache:
        # use service_started instead of service_healthy to speed up the startup
        condition: service_started
    deploy:
      replicas: 2
    networks:
      - my_company_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      start_period: 10s
      interval: 30s
      timeout: 2s
      retries: 10
  load_balancer:
    build: ./load_balancer
    ports:
      - "8080:8080"
    networks:
      - my_company_network
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      api:
        condition: service_started
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - my_company_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 2s
      retries: 10
  cdn:
    build: ./cdn
    ports:
      - "80:80"
    networks:
      - my_company_network
    volumes:
      - ./cdn/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./cdn/static:/usr/local/openresty/nginx/html/static
    depends_on:
      load_balancer:
        condition: service_started

networks:
  my_company_network:

volumes:
  cache:
    driver: local